### ISSUE TITLE
How to build and run the whole project?

### ISSUE THREAD

**Issue by qxzhou1010** [alibaba-edu/mpc4j#1]
I want to run the algorithm implemented in this repository on Linux, or MacOS. However, I can't find any documentation that tells me how to do it step by step. I've only seen compilation documentation for mpc4j-native-tool/fhe.

**Comment by liuweiran900217** [comment]
Aside from mpc4j-native-tool/fhe, this is a pure-Java library organized using Maven. We observe that the ones who are familiar with Java development can quickly run this library. For ones who are not familiar with Java, we plan to release a step-by-step guideline on how to import and run this library. I will reply when we upload such the guideline.

**Comment by liuweiran900217** [comment]
We thank @qxzhou1010 for writing a guideline for how to config the development environment on macOS. The details are in README.md.
