### ISSUE TITLE
mpc4j-native-fhe在make的进度为100%时发生“/usr/local/lib64/libseal-4.0.a: 无法添加符号: 归档没有索引；运行 ranlib 以添加一个”

### ISSUE THREAD

**Issue by aaaaaa1** [alibaba-edu/mpc4j#14]
mpc4j-native-fhe的其他条件都编译成功了，就在最后一步make发生错误，如图：
![image](https://github.com/alibaba-edu/mpc4j/assets/5926342/af8b1a86-a37b-4802-b145-6ef900ff066c)
这个问题改如何解决呢？

**Comment by aaaaaa1** [comment]
centos安装时，在cmake命令里面少了-DBUILD_SHARED_LIBS=ON

**Comment by liuweiran900217** [comment]
> centos安装时，在cmake命令里面少了-DBUILD_SHARED_LIBS=ON

Thanks for the information! We will correct README.md for mpc4j-native-fhe in 1.0.9.
