### ISSUE TITLE
PSI协议测试报错：Exception in thread "Thread-0" java.lang.IllegalArgumentException: ecc_mul failed, invalid point.

### ISSUE THREAD

**Issue by aaaaaa1** [alibaba-edu/mpc4j#16]
![1F49A65813BDF7B9E8131CDC73D7066E](https://github.com/alibaba-edu/mpc4j/assets/5926342/eedff601-bbab-48e2-8137-d2e7bf147493)
![image](https://github.com/alibaba-edu/mpc4j/assets/5926342/96d045d5-8224-4908-8777-a0bbbe4d2bf3)
 您好，运行psi的测试方法报错，这个要怎么处理才行呢？
目前有关于psi\pir的相关资料么或者交流群呢？

**Comment by liuweiran900217** [comment]
Can you paste the full error information (including the line "Java HotSpot(TM) 64-Bit Server warning: You have loaded library ..."? It seems the error comes from wrongly invoking or linking C/C++ library. Can you tell us how you generate the native library and how you run it?

**Comment by aaaaaa1** [comment]
警告信息：
1、Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/mpc4j-1.0.8/mpc4j-native-tool/cmake-build-release/libmpc4j-native-tool.so which might have disabled stack guard. The VM will try to fix the stack guard now.
2、It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

libmpc4j-native-tool.so这个库是我在Ubuntu23.04上编译，idea也是在Ubuntu23.04上运行

**Comment by liuweiran900217** [comment]
This is very strange. You can try first recompiling and installing mpc4j-native-fourq, and then mpc4j-native-tool, and finally mpc4j-native-fhe. As far as I understand, the problem relates to mpc4j-native-fourq. If you cannot success, you can email me about your contact information so that we can try to debug in person.

**Comment by qxzhou1010** [comment]
Please try using other elliptic curve types instead of FourQ to see if it passes the test. If not, please give feedback in time, and I will continue to analyze this problem.

**Comment by aaaaaa1** [comment]
这应该是我编译mpc4j-native-fourq的时候有问题，现在碰到执行make test时ecc_tests 、fp_tests测试 执行失败，看不到其他日志，所以来询问下是什么原因呢？
![image](https://github.com/alibaba-edu/mpc4j/assets/5926342/5c8f2294-b507-4a03-9e76-f6a8c570c0c6)

le@le:/home/mpc/mpc4j-1.0.8/mpc4j-native-fourq/build$ ./ecc_tests --rerun-failed --output-on-failure
--------------------------------------------------------------------------------------------------------
Testing FourQ's curve arithmetic: 
  Point doubling tests ... FAILED

**Comment by liuweiran900217** [comment]
这个问题看起来应该是微软FourQ本身的实现问题。我们只是修改了FourQ的makefile，但是并没有调整FourQ的源代码。

mpc4j可以在不使用FourQ的条件下运行协议，但需要对代码做一些修改。具体为：

1. 找到mpc4j-common-tool模块edu.alibaba.mpc4j.common.tool.crypto.ecc包下的ByteEccFactory。
2. 找到`public static ByteFullEcc createFullInstance(EnvType envType)`函数。
3. 将`return createFullInstance(ByteEccType.FOUR_Q);`修改为`return createFullInstance(ByteEccType.ED25519_SODIUM);`。

这样就可以不执行FourQ椭圆曲线。

至于FourQ为什么出错，不知是否可以提供Ubuntu系统的CPU型号？我们可以去询问FourQ的github。

**Comment by liuweiran900217** [comment]
我在FourQlib上找到了可能一样的问题：https://github.com/microsoft/FourQlib/issues/9。FourQlib本身可能并不支持某些特定的CPU。考虑这一原因，我们计划在1.0.9版本里将默认的曲线修改会ED25519，并在readme里面说明。感谢反馈的问题。

**Comment by liuweiran900217** [comment]
报的错误完全一样，还是invalid point吗？如果是，可能的原因是修改没有生效。尝试点击IntelliJ IDEA菜单栏的build -> Build Project，然后重新点击测试用例的左侧箭头。如果还是不行，请通过回帖或者邮件方式提供我任何一个在线会议软件的会议号，我远程了解一下问题。

**Comment by aaaaaa1** [comment]
按您说的修改可以了，谢谢！
咨询下关于隐私求交、匿名查询等例子的讲解文档吗？对BatchPirTest等测试例子一知半解，不是很懂
![image](https://github.com/alibaba-edu/mpc4j/assets/5926342/5a7e3455-fd5b-4b4b-9321-eeb7aa5146de)

**Comment by liuweiran900217** [comment]
PSI和PIR目前的发展速度太快，路线很多，我建议不如阅读完论文后再阅读我们的实现。目前我们也在准备一些文档，不过需要花费较长的一段时间。
