### ISSUE TITLE
FATAL_ERROR "Could not find FOUQ"

### ISSUE THREAD

**Issue by zhangtingchuang666** [alibaba-edu/mpc4j#17]
I encountered this error when compile 'mpc4j-native tool'，and I use ubuntu 22.04. I compile passed after I changed the address to absolute address. I observed that the fourq library was included under the address 'mpc4j/mpc4j-native-fourq' and there was no mention of installing fourq in compile_ubuntu.md, I did not install fourq separately. So, this problem is probably of my own making.

**Comment by lushimeng** [comment]
During the process of compiling mpc4j-native tool, I also encountered the same problem as the blogger:
[
![a065abf9248d8fe1074f3bd8e66f201](https://github.com/alibaba-edu/mpc4j/assets/64461623/1edd2560-e72b-401e-835c-a15232368081)
](url)

According to your suggestion, I compiled mpc4j-native-fourq first and passed it successfully：
[
![fa9ec360bc2f58970de102c7609488e](https://github.com/alibaba-edu/mpc4j/assets/64461623/902dc458-f4d3-400b-995b-762d028273e0)
](url)

Compiling mpc4j-native tool again still reports an error：
[
![d2ba70997a0e3b43e082a04af6b7e2d](https://github.com/alibaba-edu/mpc4j/assets/64461623/41c88b43-8f88-48fc-8482-d15d639380f6)
](url)

 How did you solve it? Looking forward for your reply, thank you.

**Comment by lushimeng** [comment]
Thank you for your reply, I don't understand what you mean, is that right?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba-edu/mpc4j"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba-edu/mpc4j] FATAL_ERROR "Could not find FOUQ" (Issue #17)





   
You need to install fours, that is, in mpc4j-native-fourq/build, run sudo make install.

**Comment by lushimeng** [comment]
The problem has been solved. I performed sudo make install in my compiled file cmake-build-release, and then compiled mpc4j-native-tool again and it was successful. Thank you very much for your help


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "alibaba-edu/mpc4j"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba-edu/mpc4j] FATAL_ERROR "Could not find FOUQ" (Issue #17)





   
You need to install fours, that is, in mpc4j-native-fourq/build, run sudo make install.

**Comment by liuweiran900217** [comment]
I have updated README.md, telling users to install fourq. Please take a look and see if this issue has been solved and close the issue if it is.
