### ISSUE TITLE
Add reference in README?

### ISSUE THREAD

**Issue by alexanderzjs** [alibaba-edu/mpc4j#2]
Highly suggest to add all paper references in README file for three purposes:

1. Track the SOTA paper implementations.
2. Provide tradeoff and benchmark references (in case bandwidth, computation resourcers are limited, they can select to switch to another solution in the repo) for business use.
3. If new SOTA is available, you can get the news ASAP.

Thanks

**Comment by liuweiran900217** [comment]
Thanks for the suggestion! 

We are in fact preparing some papers related to tradeoff and benchmark references. The reason we do not provide such references currently is that we hope our benchmark comparison can have some feedbacks from academy.

**Comment by liuweiran900217** [comment]
Hi, all:
We have released v1.0.6. See `PAPERS.md` for paper references.
