### ISSUE TITLE
关于OSN洗牌算法的两个问题。

### ISSUE THREAD

**Issue by zzx-QDU** [alibaba-edu/mpc4j#21]
刘老师，我想向您请教两个关于OSN洗牌算法的问题。
第一个问题是OSN是否能将输出调整为算术电路上的秘密分享？
第二个问题是假设OSN的输出可以调整为算术秘密分享，当输入向量中的每个元素不是一个值，而是由n个算术秘密分享组成的数组，这种情况下如何洗牌是最优解？我自己想了两个方案，一是调用2n次OSN算法进行洗牌；二是将n个值级联起来，然后调用2次OSN算法进行洗牌，但是需要在洗牌前进行A2B并且在洗牌后进行B2A。然而前者会导致OSN复杂度中与比特长度无关的固定项累加2n-2次，后者需要的两次转换成本也非常高。

感谢您的指导！

**Comment by liuweiran900217** [comment]
这个问题可能不是算法库本身的问题，我们可以换一个渠道讨论，请问可以通过邮件联系我吗？footman_900217@126.com就可以。

**Comment by zzx-QDU** [comment]
好的。
