### ISSUE TITLE
keyword PIR中的value取值问题

### ISSUE THREAD

**Issue by zlzhao998** [alibaba-edu/mpc4j#22]
keyword-pir的功能里面查询返回的key-value Map的value是固定长度的，而实际应用中这个value的长度是无法预估和保证固定长度的。 这种场景要怎么支持或改造呢？

**Comment by liuweiran900217** [comment]
PIR里面要求value是固定长度的，否则value长度本身也会泄露信息。具体实施过程中，需要预估最大长度，并通过padding方法把长度补齐。据我所知，目前还没有特别好的动态长度PIR解决方案。

**Comment by zlzhao998** [comment]
好的，感谢老师。我使用填充的方式以解决问题。
