### ISSUE TITLE
支持分布式使用吗

### ISSUE THREAD

**Issue by liyuhui666** [alibaba-edu/mpc4j#23]
如果数据量过大，比如隐私计算求交，求并这类计算，数据量较大，是否支持分布式部署使用，有相关示例吗

**Comment by liuweiran900217** [comment]
目前此算法库主要以学术研究为主，如果引入分布式计算，则需要进一步实现分布式调度等复杂问题，对于研究人员的学习成本要求较高。因此，目前mpc4j暂时没有考虑分布式部署使用，只考虑并发情况。

**Comment by liyuhui666** [comment]
![3](https://github.com/alibaba-edu/mpc4j/assets/71497399/03098e63-7e2c-4114-9345-a41e36c32646)
好的。现在有是否并发的参数，请问是否有参数控制实际并发量，使用的cpu及内存方面的参数

![4](https://github.com/alibaba-edu/mpc4j/assets/71497399/3528d09b-e08f-4a6e-bcf9-4dedc9c0e244)
我看在执行测试程序后生成结果文件名称中有并行度，这个是哪里控制的

**Comment by liuweiran900217** [comment]
此参数是通过启动jar时通过配置-Djava.util.concurrent.ForkJoinPool.common.parallelism来实现的。如果没有增加此配置项，默认为系统推荐的线程数量。
