### ISSUE TITLE
关于计算内存的疑问

### ISSUE THREAD

**Issue by liyuhui666** [alibaba-edu/mpc4j#26]
![YV UZOG%FW{~E1}%J4O2R(S](https://github.com/alibaba-edu/mpc4j/assets/71497399/9c6a191a-4323-4a58-9c85-394c6d1c6312)
以计算psi为例，关于数据输入，如果计算两方数据求交，那两个set需要放入两方的全量数据，如果读取数据量过大，比如100g大小文件，两方就是200g，如果计算节点内存较小64g，该如何使用psi求交

**Comment by lap2011** [comment]
基于mpc4j的产品化实心可以参考[DataTrust](https://help.aliyun.com/document_detail/2525370.html?spm=a2c4g.372609.0.0.52ca67a97mMQ5x)
