### ISSUE TITLE
addSubPtos的作用

### ISSUE THREAD

**Issue by zzx-QDU** [alibaba-edu/mpc4j#27]
刘老师您好，我在开发比较复杂的协议时可能会使用4个以上的子协议，这种情况下，有些子协议参与方就无法放到addSubPtos。我想知道这样会有什么影响。此外，在进行选择时，哪些子协议参与方具有更高的优先级。

感谢您的帮助！

**Comment by liuweiran900217** [comment]
我们现在也意识到应该让框架支持调用更多的子协议。不过，这个修改涉及到的点比较多，我们最早也要在1月份才能开始。现在，你可以把报错所在的检测代码暂时注释掉。

**Comment by zzx-QDU** [comment]
好的，感谢回答！

**Comment by liuweiran900217** [comment]
新发布的1.1.1版本已解决此问题，可以支持调用任意多的子协议。
