### ISSUE TITLE
关于OKVS、VODM、OVDM

### ISSUE THREAD

**Issue by AdijeShen** [alibaba-edu/mpc4j#29]
刘大佬您好，想请教下以下问题：

1. 在论文Linear Private Set Union from Multi-Query Reverse Private Membership Test（ZCL22）中，前文提到的VODM与后文中的OVDM应该是一个意思？
2. 在SKE-PSU中，用到的OVDM指向了这个实现，但里面的注释说OVDM由VOLE-PSI中提出定义，但这篇文章看起来是一个OKVS、OPPRF的方案。
https://github.com/alibaba-edu/mpc4j/blob/0a0b2fe25afa754d58dc5e2707b65c85b58256e3/mpc4j-crypto-matrix/src/main/java/edu/alibaba/mpc4j/crypto/matrix/okve/ovdm/gf2e/Gf2eOvdm.java#L6-L8
3.ZCL22中，说到SKE的VODM是由GMW协议构造的，但没有给出具体的构造方法，想知道是GMW结合SKE实现了部分功能，还是整个protocol转换成一个多方计算？这里我没太想明白是怎么做的

**Comment by liuweiran900217** [comment]
不好意思，我前两周在休假，现在才回复。

1. 前文提到的VODM和后文的OVDM是一个意思，我理解应该是笔误。
2. 论文中的OVDM指的是一个协议，这个协议包含加密、解密和VOLE-PSI里面定义的XoPaXoS（在后续论文中统一称为OKVS with Obliviousness）编码过程。代码中的OVDM指的就是OKVS with Obliviousness的编码过程。我们PSU里面的OVDM是VOLE-PSI里面XoPaXoS在mod p下的变种实现。因此，注释里的意思是，OVDM（协议）所用的OVDM（编码方法）的原始定义来自于VOLE-PSI，但我们对它进行了修改，使其支持mod p运算（而不是GF(2^l)下的运算），以和椭圆曲线兼容。
3. SKE的VODM，其基本原理是：用GMW协议实现一个LowMC，然后用GMW协议比较解密结果是否是正确的。因此，SKE的OVDM包含一个LowMC的调用+用GMW协议实现的比较过程。

**Comment by AdijeShen** [comment]
非常感谢您的回复
