### ISSUE TITLE
多线程Paillier加密引发的线程阻塞问题

### ISSUE THREAD

**Issue by Totem46831** [alibaba-edu/mpc4j#32]
mpc4j的作者您好，我想请教一个Paillier加密的问题。
我们在尝试使用多线程进行Paillier加密时遇到了线程阻塞的问题。
<img width="1306" alt="image" src="https://github.com/alibaba-edu/mpc4j/assets/134687011/873d673c-8b27-4f0f-bf52-4349afc32bc8">
继续查看阻塞线程详情，发现Block在如下位置：
<img width="585" alt="image" src="https://github.com/alibaba-edu/mpc4j/assets/134687011/b497adca-8e38-4c6e-949c-890c14efee2f">
PheEngine在加密时使用SecureRandom生成随机数，而SecureRandom在Liunx环境下生成大量随机数的场景会出现阻塞情况，具体可以参考https://blog.csdn.net/weixin_45244678/article/details/106137948
博文中提到导致阻塞的原因是因为从/dev/random中读取随机数，而/dev/random中的数据来自系统的扰动,，比如键盘输入、鼠标点击等等，当系统扰动很小时，产生的随机数不够，导致读取/dev/random的进程会阻塞等待。
以上是问题背景，现在我有几个问题想请教：
1、文章中提到我们可以从/dev/urandom读取伪随机数来解决阻塞问题，请问伪随机数是否会使算法的安全性降低？
2、在保证算法安全性不会降低的前提下，是否还有其他方式可以解决Paillier在并发加密中出现的阻塞问题？
PS：我们的项目涉及非常敏感的数据，安全等级很高，因此我们希望可以在保证安全性的基础上提升加密性能。

**Comment by liuweiran900217** [comment]
首先我想了解一下，您的问题是否是在问“随机数生成导致了阻塞”，而非“随机数生成导致加密/解密错误”？我理解您想说的是，随机数生成会导致系统无法把所有线程跑满？

1. Paillier（当然其他密码学方案也一样）要求计算过程生成随机数。这个随机数如果是\dev\random获取的，那就意味着完全随机性。如果是\dev\urandom获取的，意味着伪随机性，或者可以简单的理解为此随机数是根据某个（秘密的）种子密钥计算得来的。使用伪随机数会使得算法“随机数生成部分的安全性”依赖于伪随机数生成器的安全性。不过，目前实际中我们一般认为这种安全性降低不会引发严重的问题。实际上，互联网通信时加密数据也会用到伪随机数生成器。这里使用真随机数生成器是从密码学理论层面考虑的，在实际应用中影响不大。
2. 如果保证算法安全性（在使用伪随机数生成器的层面上）不会降低，就需要引入其他随机源。据我了解，可以使用外置芯片生成真随机数，但这涉及到对方案的改造（即实现一个新的SecureRandom，这个SecureRandom要从硬件层面读取外置芯片的伪随机数）。我理解这种开发量也不小，而且硬件IO读取代价也很高。

**Comment by Totem46831** [comment]
感谢您的回复！
是的，我们正在为“Paillier加密多线程无法跑满”一事而苦恼。根据您对\dev\urandom伪随机数生成器的理解，看起来即使是加密数据这种敏感操作，我们使用\dev\urandom已经足够安全，且不会造成阻塞。
