### ISSUE TITLE
编译phe模块的时候make报错

### ISSUE THREAD

**Issue by Handikang** [alibaba-edu/mpc4j#34]
![image](https://github.com/alibaba-edu/mpc4j/assets/42713276/a2160378-6312-477a-99a1-1c101703e20f)
我看了之前被关闭的issue，看到cmake的时候也添加了参数-DBUILD_SHARED_LIBS=ON
还是报错，如上图所示

**Comment by liuweiran900217** [comment]
看了一下报错，我理解这是编译SEAL本身时候的问题，还不涉及到mpc4j。从错误上看，似乎是因为找不到libz.a，我理解可以尝试参考https://github.com/microsoft/SEAL/issues/278，即本地执行`sudo apt-get install libz-dev`。如果仍然不能成功，可以试试通过参数`-DSEAL_USE_ZLIB=OFF`来关闭zlib。

另外，如果之前没有加-DBUILD_SHARED_LIBS=ON，则需要重新卸载SEAL（命令应该是`cmake remove`）后重新安装。

**Comment by Handikang** [comment]
@liuweiran900217 我将参数-DSEAL_USE_ZLIB调整为OFF成功了，谢谢你

**Comment by liuweiran900217** [comment]
如果没有其他问题，那我close掉此issue。

**Comment by Handikang** [comment]
可以的，谢谢啦



---原始邮件---
发件人: "Weiran ***@***.***&gt;
发送时间: 2024年4月18日(周四) 晚上6:45
收件人: ***@***.***&gt;;
抄送: "Han ***@***.******@***.***&gt;;
主题: Re: [alibaba-edu/mpc4j] 编译phe模块的时候make报错 (Issue #34)




 
如果没有其他问题，那我close掉此issue。
