### ISSUE TITLE
关于mpc4j-s2pc-aby模块中测试报错的问题

### ISSUE THREAD

**Issue by Handikang** [alibaba-edu/mpc4j#37]
![image](https://github.com/alibaba-edu/mpc4j/assets/42713276/e9e77c81-d8f7-4f19-83d6-8d9fc99fc6c6)
我前置编译工作已经完成，用的是jdk17编译的，是连接的wsl2(ubuntu20.04),运行HammingTest测试的时候，报错如上图所示，下图是我的运行配置
![image](https://github.com/alibaba-edu/mpc4j/assets/42713276/20cdb4e7-77f3-4473-8c8c-bc01a64cd922)

**Comment by liuweiran900217** [comment]
这是FourQ里面的一个bug，你可以先检查一下安装FourQ时的make test是否存在报错的情况。我在readme.md里面的”Notes for Errors on FourQlib“写有下述描述：

> When you run `make test` for `mpc4j-native-fourq`, you possibly meet test failures. The reason is that the original [FourQlib](https://github.com/microsoft/FourQlib) have some unknown bugs when running on some platforms (but currently we do not know which platforms you may meet the bug). See [Issue #9](https://github.com/microsoft/FourQlib/issues/9) in FourQlib and [Issue #16](https://github.com/alibaba-edu/mpc4j/issues/16) in `mpc4j`.

> Simply ignoring the error is OK, but many test cases in `mpc4j` would fail since `mpc4j` uses FourQ EC curve by default. You need to change the default EC curve from FourQ to ED25519 (also see [Issue #16](https://github.com/alibaba-edu/mpc4j/issues/16) in `mpc4j` for more details):

> 1. In module `mpc4j-common-tool`, find `ByteEccFactory` in package `edu.alibaba.mpc4j.common.tool.crypto.ecc`.
> 2. Find the function `public static ByteFullEcc createFullInstance(EnvType envType)`.
> 3. Change `return createFullInstance(ByteEccType.FOUR_Q);` to `return createFullInstance(ByteEccType.ED25519_SODIUM);`.

**Comment by Handikang** [comment]
是的，测试fourq的时候确实出现了错误，这时候我是否需要更换其他的椭圆曲线
![image](https://github.com/alibaba-edu/mpc4j/assets/42713276/9349e60c-24db-4380-a7ad-b883d4739ac3)

**Comment by liuweiran900217** [comment]
请根据我上面给出的说明修改代码（以从FourQ更新为ED25519）

**Comment by Handikang** [comment]
感谢你，可以运行了 @liuweiran900217
