### ISSUE TITLE
运行测试程序报错

### ISSUE THREAD

**Issue by Handikang** [alibaba-edu/mpc4j#39]
基于mpc4j1.0.8写了一个测试程序，我使用了这个启动参数，报错如下，想问下是什么问题

-Djava.library.path=/issue/2pc/mpc4j/mpc4j-native-tool/cmake-build-release:/issue/2pc/mpc4j/mpc4j-native-fhe/cmake-build-release

![image](https://github.com/alibaba-edu/mpc4j/assets/42713276/2bbf261a-6575-46d3-a944-c376e97dcee0)
![image](https://github.com/alibaba-edu/mpc4j/assets/42713276/fa7dec7c-ba8e-407c-a5a1-c1ff65106c3e)

**Comment by liuweiran900217** [comment]
这应该是FourQ导致的，请参见：https://github.com/alibaba-edu/mpc4j/issues/37，应该就可以解决问题。
