### ISSUE TITLE
Empty private constructors

### ISSUE THREAD

**Issue by damesca** [alibaba-edu/mpc4j#4]
I have noticed that many classes have **// empty** inside the private constructor, which I assume is the way to instantiate those classes. Is it todo work? Many tests do not work for me with errors like: "could not initialize class X..."

**Comment by liuweiran900217** [comment]
Can you provide some test examples?

The private constructors with empty body are classes that can be created with static methods like "createFrom" or methods with similar names.

Another possible problem is the constructor complains not finding the related native library. This may occur if the -Djava.library.path is not correctly set or the native library is not compiled correctly.

**Comment by damesca** [comment]
Yes, it was my fault, just a problem linking the native libraries. Inspecting the source code led me to a wrong conclusion. 

Thanks a lot for your time!
