### ISSUE TITLE
关于并行线程数量的问题

### ISSUE THREAD

**Issue by yu1bo** [alibaba-edu/mpc4j#44]
请问下当设置parallel=true时，程序是以多少的线程数执行的呢

**Comment by liuweiran900217** [comment]
如果设置`parallel=true`，则程序会按照JVM默认的LocalThreadPool线程数量来执行程序。可以通过打印`ForkJoinPool.commonPool().getParallelism()`的返回值查看默认线程数量。`mpc4j`的输出结果的文件里也包含了线程数量。

如果想控制线程数量，可以在执行`java`命令时增加参数`-Djava.util.concurrent.ForkJoinPool.common.parallelism=x`，其中x是你想运行的线程数量。

详细内容可以参见：https://stackoverflow.com/questions/49009662/set-java-util-concurrent-forkjoinpool-common-parallelism-java-property。

**Comment by yu1bo** [comment]
谢谢
