### ISSUE TITLE
FileRpc test fail

### ISSUE THREAD

**Issue by hanfeng1996** [alibaba-edu/mpc4j#5]
When running the RpcTest, we found one error message "Cannot delete file XXX_PAYLOAD".
The reason is that "bufferedReader.close()"(line239) should be called before "deleted = payloadFile.delete()"(line234) in the function "DataPacket receive(DataPacketHeader header)" of "FileRpc.java".

**Comment by liuweiran900217** [comment]
Thanks for the bug report! It seems there is no error occurs when running this test case on Mac or Linux. Do you find this error on Mac / Linux, or on other platform like Windows?
