### ISSUE TITLE
尊敬的作者大大，能不能捐赠我一份论文PDF

### ISSUE THREAD

**Issue by 982945902** [alibaba-edu/mpc4j#9]
"Scape: Scalable Collaborative Analytics System on Private Database with Malicious Security"

**Comment by liuweiran900217** [comment]
Hi, I will ask the first author of this paper add see if he can share the paper to you.

**Comment by hanfeng1996** [comment]
Please leave your email here.

**Comment by 982945902** [comment]
> Please leave your email here.

982945902@qq.com

**Comment by 982945902** [comment]
感谢两位阿里大佬 @liuweiran900217 @hanfeng1996
